[package]
name = "unoserver"
version = "0.1.0"
authors = ["Enzo Strongoli <enzo@sport.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
uuid = { version = "0.8.1", features = ["v4"] }